### ISSUE TITLE
missing TE header

### ISSUE THREAD

**Issue by mbruce** [doctorseus/grpc-dotnet-unity#1]
Getting this on the server:  NettyServerHandler [WARNING] (grpc-nio-worker) - Expected header TE: trailers, but null is received. This means some intermediate proxy may not support trailers

This results in the client getting:  Error:  One or more errors occurred.  (Status(StatusCode="Cancelled", Details="No grpc-status found on response."))

**Comment by Benedicht** [comment]
It's already got fixed in Best HTTP/2, but it's not released yet. I plan to release it in one or two weeks, but if you drop me a mail at besthttp@gmail.com or ping me at the plugin's [discord channel](https://discord.gg/yD9tXwQ) i can give a download link to an updated package.

**Comment by mbruce** [comment]
resolved by an update to Best HTTP/2.  Closing.
