### ISSUE TITLE
Handling disconnect from the server

### ISSUE THREAD

**Issue by igor84** [doctorseus/grpc-dotnet-unity#3]
When I make a plain C# console app that acts as a grpc client and I call a grpc method that returns a stream then `await call.ResponseStream.MoveNext()` throws the exception bellow when I kill the server:

```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error reading next message. IOException: The request was aborted. IOException: Unable to read
data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host."
, DebugException="System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
```

But when I use GRPCBestHttpHandler in Unity no exception is thrown upon killing the server and the await just keeps waiting. I don't see any obvious way to detect disconnects on client side without this?

**Comment by igor84** [comment]
Also if I call unary calls like this:
```c#
for (var i = 0; i < 20; i++)
{
	reply = await client.SayHelloAsync(new HelloRequest {Name = "MyName" + i});
	Console.WriteLine($"Got reply: {reply}");
	await Task.Delay(1000);
}
```

In C# console app I get an exception after some time from killing the server. But if I manage to restart the server in less than 5s client app just resumes working without any errors.

In Unity there is no Exception nor does it resume working after fast restart.

**Comment by doctorseus** [comment]
Hi @igor84 , thanks for reporting. From looking at the code, we only close the `PushPullStream(incoming)` in case the call has completed with a status. But in reality I believe we would have to also close it in the error case (in this case the HTTP2 being closed by the server). As this is not happening GRPC probably keeps blocking on `PushPullStream.Read` and `MoveNext` will never return.

This should be fixable, I might be able to get to that on the weekend. If you find a solution ealier feel free to share. :-)

I can't comment on the reconnection. That will be more visible once we have the first issue fixed.

**Comment by igor84** [comment]
I agree, it should be that Grpc handles the reconnect after error and BestHttp just needs to properly report the error.

**Comment by doctorseus** [comment]
@igor84 could you give #4 a try. I tried to handle initial connection issues (server is already down) and the issue of unexpected disconnects which you initially reported here. Let me know if you see anything else related to this which we should handle.

I think this should also resolve your issues with the unary calls.

**Comment by igor84** [comment]
Thanks for the quick reply. I tried the fix and it kind of fixes everything reported. Unary calls fail within 5 seconds of killing the server just like in the plain C# implementation and they automatically resume if I restart the server quick enough.

But streaming call MoveNext method fails after 15s or more while in plain C# it fails almost immediately after killing the server.

**Comment by Benedicht** [comment]
@igor84

> But streaming call MoveNext method fails after 15s or more while in plain C# it fails almost immediately after killing the server.

It might be because the plugin has a 30 seconds ping frequency, and if there's nothing to send to the server, it takes time to detect that the server isn't available (or if there's a network error).

You can try out adding the following line somewhere in your startup code:
`BestHTTP.HTTPManager.HTTP2Settings.PingFrequency = TimeSpan.FromSeconds(1);`

More frequent pings mean more overhead.

**Comment by igor84** [comment]
That makes sense and indeed using that settings make the call fail much faster. Make you wonder though, how they manage to always detect disconnects so fast in plain C# implementation...

**Comment by doctorseus** [comment]
Great that it seems to work.

@ disconnect delay.
On the server and client side, how does your setup look like (what versions and implementations do you use on either side and what OS are you running this, do server and client run on the same machine)?
I didn't notice any long delay between killing the Java server and receiving the "unexpected disconnect" exception on the client while testing on localhost. Certainly not 15s. But as Tivadar already said, this is most likley connected to the timeouts and ping intervals on the client side. But it could also be related to the TCP RST package.
However,  as for how it is implemented now is that as soon as BestHTTP marks the request as completed for whatever reason it will trigger the grpc termination.

**Comment by igor84** [comment]
I am testing this on Windows. I made a C# Grpc server using the latest Grpc.AspNetCore.2.51.0 and also in Unity Grpc.Net.Client.2.51.0 package. Server is running on a local machine so the client code is targeting it through localhost url. It could be that I just didn't test enough and maybe I just got lucky with fast disconnects in plain C# version the few times I tried it :)

**Comment by Benedicht** [comment]
You can detect a TCP connection loss only by sending data. Almost every layers define its own one: TCP, TLS and HTTP/2 too. The plugin uses only HTTP/2's ping mechanism. Experimented with TCP keepalives a couple of years ago, but there's no direct support in the .net runtime, only to enable it (what the plugin does) but the default timer intervals are **24 hours** on windows if i remember correctly.

Remnants of these are still there in the `\Best HTTP\Source\PlatformSupport\TcpClient\TcpClient.cs` file.
Tryied to set different timer values, but when it went live i got reports on connection issues and false positives.

**Comment by Benedicht** [comment]
It seems that they have support now: https://github.com/dotnet/runtime/issues/24041
However, it's not in .net standard 2.1.

Setting the values with IOControl still works, however it seems a little different (no retry count value for example) and passed values are treated as milliseconds instead of seconds (and only works under windows).

**Comment by igor84** [comment]
I noticed one more issue. I changed the server handler to throw an Exception. In plain C# client I get this `Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")`. In Unity I first got an error that you can't pass null Exception to `grpcResponseTask.SetException` in GRPCBestHttpHandler so I changed that line to:
```c#
grpcResponseTask.SetException(request?.Exception ?? new Exception("Exception was thrown by handler"));
```
But it would be nice if we could somehow get that StatusCode and Detail data...

**Comment by igor84** [comment]
Managed to solve that by replacing that line with this:

```c#
var exception = request?.Exception;
if (exception == null && response != null &&
    response.Headers.TryGetValue("grpc-status", out var strStatus) &&
    int.TryParse(strStatus[0], out var status))
{
	var message = "UnknownError";
	if (response.Headers.TryGetValue("grpc-message", out var messages))
	{
		message = messages[0];
	}

	exception = new RpcException(new Status((StatusCode) status, message));
}

exception ??= new RpcException(new Status(StatusCode.Unknown, "Exception was thrown by handler"));

grpcResponseTask.SetException(exception);
```

**Comment by Benedicht** [comment]
@igor84 Where is this go?
The `HTTPRequest` has a `Status` property that can be used to check for any errors: [Error handling topic](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/http/ErrorHandling.html)

The `Exception` property for example is populated only when the request is in the Error state. The topic linked above is for when the Status is checked in the callback when the State isn't change any more.

**Comment by igor84** [comment]
In this case request.State is Finished and response.StatusCode is 200 but grpc error is in the headers. I will put the code in the pull request comment so it is clear where it should be.

**Comment by doctorseus** [comment]
@igor84 I force pushed the branch, would be great if you could give it a shot. It should follow the grpc spec more closely now and handle all cases where we actually have a response (with a status message).

**Comment by igor84** [comment]
Thank you very much for quick response. I tried it now and it handled server shutting down and server throwing RpcException with custom message as expected. I got the proper RpcException with proper data on the client.

The only thing left is that in plain C# if I have a loop that does unicast calls every second:
```c#
for (var i = 0; i < 20; i++)
{
  var reply = await client.SayHelloAsync(new HelloRequest {Name = "MyName" + i});
  Console.WriteLine($"Got reply: {reply}");
  await Task.Delay(1000);
}
```
and I kill the server, I can most often restart the server quick enough that no exception happens on the client and it just continues working but in Unity I always get an Exception.

This problem is not critical though since if I add try catch inside the loop and just try again after Exception happens the next request again succeeds.

**Comment by igor84** [comment]
Also when I am calling MoveNext for server streaming BestHttp writes this error log when I kill the server:
```
{"tid":1613,"div":"HTTP2Handler","msg":"Sender thread","ex": [{"msg": "Cannot write application data on closed\/failed TLS connection", "stack": "  at BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsProtocol.WriteApplicationData (System.ReadOnlySpan`1[T] buffer) [0x0002e] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\SecureProtocol\\tls\\TlsProtocol.cs:1081 \r\n  at BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsProtocol.WriteApplicationData (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0000a] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\SecureProtocol\\tls\\TlsProtocol.cs:994 \r\n  at BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00001] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\SecureProtocol\\tls\\TlsStream.cs:92 \r\n  at BestHTTP.Extensions.WriteOnlyBufferedStream.Flush () [0x0000f] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\Extensions\\WriteOnlyBufferedStream.cs:35 \r\n  at BestHTTP.Connections.HTTP2.HTTP2Handler.RunHandler () [0x00c06] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\Connections\\HTTP2\\HTTP2Handler.cs:461 "}],"stack":"  at Connections.HTTP2.HTTP2Handler.RunHandler () [0x00c4c] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\Connections\\HTTP2\\HTTP2Handler.cs:468 \r  at Connections.HTTPConnection.ThreadFunc () [0x002ac] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\Connections\\HTTPConnection.cs:196 \r  at PlatformSupport.Threading.ThreadedRunner+<>c__DisplayClass6_0.<RunLongLiving>b__0 () [0x00000] in C:\\git\\sharedpackages\\UnityPackageTester\\Assets\\Best HTTP\\Source\\PlatformSupport\\Threading\\ThreadedRunner.cs:107 \r  at System.Threading.Tasks.Task.InnerInvoke () [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.Tasks.Task.Execute () [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.Tasks.Task.ExecutionContextCallback (System.Object obj) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task& currentTaskSlot) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.Tasks.Task.ExecuteEntry (System.Boolean bPreventDoubleExecution) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0 (System.Object s) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 \r  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00000] in <c9d3ffd4b98649ee9989e1908eaca019>:0 ","ctxs":[{"TypeName": "HTTP2Handler", "Hash": -65088090275841, "Connection": 1010902506}],"t":638110303877544601,"ll":"Exception","bh":1}
```

**Comment by Benedicht** [comment]
@igor84 That's nothing to worry about, it's just printing out the exception that got thrown because of the killed server.

**Comment by doctorseus** [comment]
@igor84 I made a new v1.1.0 release with the latest changes. And it also includes call cancellation support.

> I can most often restart the server quick enough that no exception happens on the client and it just continues working but in Unity I always get an Exception.

Currently there is no retry mechanism from the handler itself, but there is a setting for BestHTTP for retrying https://github.com/doctorseus/grpc-dotnet-unity/blob/master/Assets/GRPC.NET/Scripts/GRPCBestHttpHandler.cs#L33 which we disable (anyway only enabled for GET requests by default afaik). You could try modifying this to see if it helps your case. In general I don't plan to modify the retry behavior at this point as I believe it should be handled either by gRPC or the application itself.

**Comment by igor84** [comment]
That sounds reasonable. Thank you very much for all the support.
