### ISSUE TITLE
webgl platform build fail.

### ISSUE THREAD

**Issue by tangdading6** [doctorseus/grpc-dotnet-unity#8]
error:

Assets/GRPC.NET/Scripts/GRPCBestHttpHandler.cs(10,28): error CS0234: The type or namespace name 'HTTP2' does not exist in the namespace 'BestHTTP.Connections' (are you missing an assembly reference?)

**Comment by doctorseus** [comment]
Hi @tangdading6, HTTP2 is not supported on the web directly, it is instead implemented by the browser itself. If you are interested in using gRPC via HTTP (1) you can check out:
- https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md
- https://learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-7.0

The intention of this package (and its usage of BestHttp2) is to support gRPC via HTTP2 on native Unity platforms (as Unity does not ship with HTTP2 support at this point of time).

You need neither if you just target web builds. But you will always be limited to the featureset gRPC-web supports.

Let me know if you have any more questions, closing it for now as its not applicable.
